### ISSUE TITLE
Custom armor

### ISSUE THREAD

**Issue by x-j0nnay-x** [Choonster-Minecraft-Mods/TestMod3#2]
Hey can you give me a link to where i can find the coding for rendering the armor model, for some reason its searching for _layer_1 but is not putting the name of my armor, im really at a loss.

**Comment by Choonster** [comment]
This isn't the place to ask these questions. Create a thread in the Modification Development section of Minecraft Forum or the Modder Support section of the Minecraft Forge Forum and someone (possibly me) will answer you there.
