### ISSUE TITLE
cant setup gradle

### ISSUE THREAD

**Issue by loordgek** [Choonster-Minecraft-Mods/TestMod3#5]
https://gist.github.com/anonymous/7f0e948fe04d67fdbdd7239352860f36

**Comment by Choonster** [comment]
That's strange, Gradle should be downloading the Grgit plugin. Which version of Gradle are you using?

Could you run it with the `--stacktrace` and `--debug` options and post that log?

**Comment by loordgek** [comment]
https://gist.github.com/loordgek/d2832890402bfde355505d542d129c63

**Comment by Choonster** [comment]
Did you clone the repository using Git or download it as a ZIP file?

The buildscript currently requires the mod to be in a Git repository so it can append the latest commit ID to the version. I can probably remove this requirement.

**Comment by loordgek** [comment]
i did download as zip,
can you put that in the readme

**Comment by Choonster** [comment]
I've removed the requirement on the Git repository, it will now simply fall back to `NOGIT` as the commit ID part of the version.
