### ISSUE TITLE
help me w/ item variants

### ISSUE THREAD

**Issue by loordgek** [Choonster-Minecraft-Mods/TestMod3#6]
https://gist.github.com/anonymous/59e8d6345d5ab583e5ec9bc6a45f7434

https://github.com/loordgek/Extragenarators/blob/trytofix/src/main/resources/assets/extragenarators/blockstates/upgrade.json

https://github.com/loordgek/Extragenarators/blob/trytofix/src/main/java/loordgek/extragenarators/enums/EnumItems.java

i can not get item variants textures to work

i asked it the forge forum http://www.minecraftforge.net/forum/topic/44703-need-help-w-textures-block-and-item/?page=2 but that did not realy work

**Comment by Choonster** [comment]
I don't offer modding help via GitHub issues, you need to follow up on your existing thread.
