### ISSUE TITLE
DummyRecipe, minus the warnings

### ISSUE THREAD

**Issue by tseeker** [Choonster-Minecraft-Mods/TestMod3#7]
The following, while a bit dirty, gets rid of the warnings about resources from the wrong mod:

	public DummyRecipe( final ResourceLocation location )
	{
		try {
			@SuppressWarnings( "rawtypes" )
			final Class< IForgeRegistryEntry.Impl > cls = IForgeRegistryEntry.Impl.class;
			final Field fld = cls.getDeclaredField( "registryName" );
			fld.setAccessible( true );
			fld.set( this , location );
		} catch ( NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException e ) {
			throw new RuntimeException( "Apparently, LexManos doesn't approve." , e );
		}
	}

**Comment by Choonster** [comment]
That's a nice trick, but I think it's a bit too hackish. I try to keep this mod as a rough guide to the "best practises", so I don't want to mess with Forge's internals unless strictly necessary.

Thanks anyway.

**Comment by tseeker** [comment]
Oh, yeah, definitely not good practice - but I was looking for a way to do it and saw the post in which you were considering switching the active ModContainer, so I thought I'd mention it. Thanks for your test mods, by the way, they're a great resource.

(I don't remember whether commenting will reopen the issue - that's not the goal, if so, I'm sorry)
